kind = "web"
previewPath = "/"
title = "Csíkszereda Programajánló"
version = "1.0.0"
id = "artifacts/csikszereda-programajanlat"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20385

[services.development]
run = "pnpm --filter @workspace/csikszereda-programajanlat run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/csikszereda-programajanlat", "run", "build" ]
publicDir = "artifacts/csikszereda-programajanlat/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20385"
BASE_PATH = "/"
