// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/majalis-variants/PlakatSzinek.tsx": () => import("../components/mockups/majalis-variants/PlakatSzinek.tsx"),
  "./components/mockups/majalis-variants/SotetSmaragd.tsx": () => import("../components/mockups/majalis-variants/SotetSmaragd.tsx"),
  "./components/mockups/hirlevel/Hirlevel.tsx": () => import("../components/mockups/hirlevel/Hirlevel.tsx")
};
